### PR TITLE
Add support for MAK keys

### PR DESCRIPTION
**Pull request by jdval**
I've only tested this with win7, but it works there and then assuming the clock inside the VM is set properly, activation online works as well.

### CODE REVIEW

**Comment by jdval** [comment]
Are there any issues with this PR I can help with to move it along?

**Comment by jbremer** [comment]
Thanks for your contribution :-) Somebody needs to verify that everything is still working etc which takes a bit of time, but otherwise it's looking good. Would also be useful if you could share example usage & some background on MAK keys (first time I hear about it). Thanks!

**Comment by jdval** [comment]
I've since tested with win10x64 and it works there as well.
FWIW, I believe this is related to PR #106 . 
MAKs are Multiple Activation Keys, it's the type of key that we get from our MSDN (now [Visual Studio Pro](https://visualstudio.microsoft.com/vs/pricing/)). When I first tried vmcloak with the MAK key, I got an error during setup about "invalid license key", which led me to discovering that [MAK keys have to go in a different section](https://blogs.technet.microsoft.com/askcore/2009/10/05/invalid-product-key-error-specifying-mak-key-in-unattend-xml/) of the unattend.xml file.

This patch doesn't change any of the default behaviour, but gives you the option to add a `--serial-key-type` argument to specify that the serial key being provided is a MAK key, and then modifying the XML appropriately.

Example usage (I'm using 'iso' machinery here and then building a KVM VM):

`vmcloak init --win10x64 --iso-mount /mnt/win10/ --serial-key ABCD-EFGH-IJKL-MNOP -v --vm iso --serial-key-type mak win10vmctest`

**Comment by Brueggus** [comment]
This feature would be really useful!

**Pull request closed without merging**
